# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2.10

# Define an environment variable
env:
  - SYMFONY_VERSION="3.4.*" DB=mysql

# Update composer
before_install:
  - composer self-update
  - composer install

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load --fixtures src/YZ/EcommerceBundle/DataFixtures/ORM/LoadCategory.php --append
  - php bin/console doctrine:fixtures:load --fixtures src/YZ/EcommerceBundle/DataFixtures/ORM/LoadTva.php --append
  - php bin/console doctrine:fixtures:load --fixtures src/YZ/EcommerceBundle/DataFixtures/ORM/LoadProduct.php --append

# Run script
script:
  - sudo ./vendor/bin/simple-phpunit